version: '3.8'

services:
  db:
    container_name: postgres_pdf
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    container_name: judge_pdf
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@db:5432/$DB_NAME
    ports:
      - "8000:8000"

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
